export type Locale = 'ur' | 'en'

export const BUSINESS_NAME: Record<Locale, string> = {
  ur: 'جواد ٹریڈرز',
  en: 'Jawad Traders',
}

const LABELS_UR = {
  dashboard: 'ڈیش بورڈ',
  name: 'نام',
  phone: 'فون نمبر',
  date: 'تاریخ',
  type: 'قسم',
  save: 'محفوظ کریں',
  cancel: 'منسوخ',
  search: 'تلاش کریں...',
  noData: 'کوئی ڈیٹا نہیں',
  actions: 'عمل',
  total: 'کل',
  login: 'لاگ ان',
  signup: 'سائن اپ',
  email: 'ای میل',
  password: 'پاس ورڈ',
  confirmPassword: 'پاس ورڈ کی تصدیق',
  loginButton: 'لاگ ان کریں',
  signupButton: 'اکاؤنٹ بنائیں',
  logout: 'لاگ آؤٹ',
  noAccount: 'اکاؤنٹ نہیں ہے؟',
  haveAccount: 'پہلے سے اکاؤنٹ ہے؟',
  loginError: 'ای میل یا پاس ورڈ غلط ہے',
  signupError: 'اکاؤنٹ بنانے میں خرابی ہوئی',
  passwordMismatch: 'پاس ورڈ ملتے نہیں ہیں',
  signupSuccess: 'اکاؤنٹ کامیابی سے بن گیا! اب لاگ ان کریں',
  emailNotConfirmed: 'ای میل کی تصدیق ابھی نہیں ہوئی۔ پہلے ای میل چیک کریں',
  clients: 'کلائنٹس',
  addClient: 'نیا کلائنٹ',
  editClient: 'کلائنٹ میں ترمیم',
  deleteClient: 'حذف کریں',
  deleteConfirm: 'کیا آپ واقعی حذف کرنا چاہتے ہیں؟',
  clientName: 'کلائنٹ کا نام',
  clientPhone: 'فون نمبر',
  items: 'اشیاء',
  addItem: 'نئی شے',
  itemName: 'شے کا نام',
  quantity: 'مقدار',
  viewItems: 'اشیاء دیکھیں',
  eveningSummary: 'شام کا خلاصہ',
  itemsPerClient: 'فی کلائنٹ اشیاء',
  totalQuantityPerItem: 'فی شے کل مقدار',
  totalItems: 'کل اشیاء',
  vegetableInventory: 'سبزی انوینٹری',
  vegetableName: 'سبزی کا نام',
  bought: 'خریداری',
  sold: 'فروخت',
  remaining: 'باقی',
  addVegetable: 'سبزی شامل کریں',
  dailyTotals: 'روزانہ کا حساب',
  chickenManagement: 'مرغی مینجمنٹ',
  chickenBought: 'مرغی خریدی',
  chickenSold: 'مرغی فروخت',
  numberOfChickens: 'مرغیوں کی تعداد',
  weightKg: 'وزن (کلو)',
  recordBought: 'خریداری درج کریں',
  recordSold: 'فروخت درج کریں',
  totalBought: 'کل خریداری',
  totalSold: 'کل فروخت',
  remainingQuantity: 'باقی تعداد',
  remainingWeight: 'باقی وزن (کلو)',
  reports: 'رپورٹس',
  dailySalesReport: 'روزانہ فروخت رپورٹ',
  remainingStockReport: 'باقی اسٹاک رپورٹ',
  clientWiseReport: 'کلائنٹ وائز رپورٹ',
  vegetablesSold: 'سبزیاں فروخت',
  chickenSoldReport: 'مرغی فروخت',
  totalWeight: 'کل وزن',
  stock: 'اسٹاک',
  home: 'ہوم',
  navAbout: 'ہمارے بارے میں',
  navContact: 'رابطہ',
  tagline: 'قابل اعتماد تجارت اور سپلائی خدمات',
  heroDesc: 'گیس سلنڈرز، تازہ مرغی اور سبزیوں کی فراہمی میں آپ کا بھروسہ مند ساتھی۔ مسلسل سپلائی، مناسب قیمتیں اور طویل مدتی کاروباری تعلقات۔',
  heroCta: 'رابطہ کریں',
  ourServices: 'ہماری خدمات',
  gasCylinders: 'گیس سلنڈرز',
  gasCylindersMainBiz: 'بنیادی کاروبار',
  gasCylindersDesc: 'ایل پی جی اور آکسیجن سلنڈرز کی قابل اعتماد فراہمی — گھریلو اور تجارتی ضروریات کے لیے۔ حفاظت، بروقت ترسیل اور بھروسہ مند سروس ہماری ترجیح ہے۔',
  chickenTrading: 'تازہ مرغی',
  chickenTradingDesc: 'تازہ مرغی کی روزانہ خرید و فروخت۔ معیار اور تازگی ہماری ضمانت ہے۔',
  vegetableTrading: 'تازہ سبزیاں',
  vegetableTradingDesc: 'معیاری سبزیوں کی روزانہ فراہمی۔ تازگی اور مناسب حفاظت کے ساتھ۔',
  aboutUs: 'ہمارے بارے میں',
  aboutDesc: 'جواد ٹریڈرز ایک معتبر تجارتی ادارہ ہے جو گیس سلنڈرز کی فراہمی اور تقسیم میں مہارت رکھتا ہے۔ ہم اپنے صارفین کو بہترین سروس فراہم کرنے کے لیے پرعزم ہیں۔',
  whyChooseUs: 'ہمیں کیوں چُنیں؟',
  trustedLocal: 'بھروسہ مند کاروبار',
  trustedLocalDesc: 'مقامی طور پر قائم، برسوں سے صارفین کا اعتماد',
  consistentSupply: 'مسلسل سپلائی',
  consistentSupplyDesc: 'بلا تعطل فراہمی کا نظام، ہمیشہ دستیاب',
  fairDealing: 'شفاف لین دین',
  fairDealingDesc: 'منصفانہ قیمتیں اور واضح کاروباری طریقے',
  customerFocused: 'صارف مرکوز سروس',
  customerFocusedDesc: 'آپ کی ضروریات ہماری ترجیح ہیں',
  contactUs: 'رابطہ کریں',
  phoneWhatsApp: 'فون / واٹس ایپ',
  emailLabel: 'ای میل',
  serviceArea: 'سروس ایریا',
  serviceAreaValue: 'صنوبر سٹی (گرین ولاز) لائن 3',
  businessHours: 'کاروباری اوقات',
  businessHoursValue: 'ہفتے کے 7 دن\nصبح 7:30 تا رات 12:00',
  chatOnWhatsApp: 'واٹس ایپ پر بات کریں',
  footerDesc: 'گیس سلنڈرز، تازہ مرغی اور سبزیوں کی فراہمی میں آپ کا بھروسہ مند ساتھی',
  footerTagline: 'معیاری سپلائی جس پر آپ اعتماد کر سکتے ہیں',
  allRightsReserved: 'جملہ حقوق محفوظ ہیں',
  cylinderTypes: 'سلنڈر اقسام',
  addCylinderType: 'نئی قسم شامل کریں',
  cylinderName: 'سلنڈر کا نام',
  cylinderWeightKg: 'وزن (کلو)',
  cylinderPrice: 'سلنڈر کی قیمت',
  gasPrice: 'گیس کی قیمت',
  noOfCylinders: 'سلنڈروں کی تعداد',
  editCylinderType: 'ترمیم کریں',
  noCylinderTypes: 'کوئی سلنڈر قسم نہیں',
  settings: 'ترتیبات',
  manageVegetables: 'سبزیوں کی فہرست',
  addVegetableName: 'نئی سبزی شامل کریں',
  noVegetableNames: 'کوئی سبزی شامل نہیں',
  editVegetableName: 'ترمیم کریں',
  duplicateName: 'یہ نام پہلے سے موجود ہے',
  cylinderAssignments: 'سلنڈر تفویض',
  assignCylinder: 'سلنڈر دیں',
  selectClient: 'کلائنٹ منتخب کریں',
  selectCylinderType: 'سلنڈر کی قسم منتخب کریں',
  available: 'دستیاب',
  noCylinderAssignments: 'اس تاریخ کی کوئی تفویض نہیں',
  notEnoughCylinders: 'اتنے سلنڈر دستیاب نہیں',
  assigned: 'تفویض شدہ',
  soldExceedsRemaining: 'فروخت باقی مقدار سے زیادہ نہیں ہو سکتی',
  unit: 'یونٹ',
  priceBought: 'خریداری قیمت',
  priceSold: 'فروخت قیمت',
  unitKg: 'کلو',
  unitDozen: 'درجن',
  unitPiece: 'عدد',
  unitCrate: 'پیٹی',
  unitSack: 'بوری',
  todaySummary: 'آج کا خلاصہ',
  cylindersAssignedToday: 'آج تفویض شدہ سلنڈر',
  totalCylinders: 'کل سلنڈر',
  unassigned: 'غیر تفویض شدہ',
  vegetableSummary: 'سبزی خلاصہ',
  totalBuyPrice: 'کل خریداری قیمت',
  totalSellPrice: 'کل فروخت قیمت',
  chickenSummary: 'مرغی خلاصہ',
  totalQuantity: 'کل تعداد',
  profitLoss: 'نفع / نقصان',
  profit: 'نفع',
  loss: 'نقصان',
  price: 'قیمت',
  dailySales: 'روزانہ فروخت',
  openingStock: 'افتتاحی اسٹاک',
  totalGasKg: 'کل گیس (کلو)',
  totalCylindersOpening: 'کل سلنڈر',
  saveDayOpening: 'محفوظ کریں',
  customerName: 'گاہک کا نام',
  phoneNumber: 'فون نمبر',
  totalAmount: 'کل رقم',
  paid: 'ادائیگی',
  balance: 'بیلنس',
  addSale: 'فروخت شامل کریں',
  noDailySales: 'آج کی کوئی فروخت نہیں',
  newCustomer: 'نیا گاہک',
  customerBalance: 'گاہک بیلنس',
  totalPaid: 'کل ادائیگی',
  totalRemaining: 'کل باقی',
  editOpening: 'ترمیم',
  saleType: 'فروخت کی قسم',
  gas: 'گیس',
  other: 'دیگر',
  gasKgSold: 'گیس (کلو)',
  filterByName: 'نام سے تلاش',
  filterByPhone: 'فون سے تلاش',
  previous: 'پچھلا',
  next: 'اگلا',
  page: 'صفحہ',
  totalSale: 'کل فروخت',
  successSaved: 'کامیابی سے محفوظ ہوا',
  successDeleted: 'کامیابی سے حذف ہوا',
  errorOccurred: 'خرابی ہوئی',
  salary: 'تنخواہ',
  employeeName: 'ملازم کا نام',
  totalPay: 'کل تنخواہ',
  addSalary: 'تنخواہ شامل کریں',
  editSalary: 'تنخواہ میں ترمیم',
  totalSalaries: 'کل تنخواہیں',
  totalPaidSalary: 'کل ادا شدہ',
  totalRemainingSalary: 'کل باقی',
  month: 'مہینہ',
  newEmployee: 'نیا ملازم',
  noSalaryRecords: 'اس مہینے کا کوئی ریکارڈ نہیں',
  employeeBalance: 'ملازم بیلنس',
  suppliers: 'سپلائرز',
  supplierName: 'سپلائر کا نام',
  addSupplier: 'سپلائر شامل کریں',
  editSupplier: 'سپلائر میں ترمیم',
  totalBill: 'کل بل',
  totalPaidSupplier: 'کل ادا شدہ',
  totalRemainingSupplier: 'کل باقی',
  noSuppliers: 'کوئی سپلائر نہیں',
  newSupplier: 'نیا سپلائر',
} as const

const LABELS_EN = {
  dashboard: 'Dashboard',
  name: 'Name',
  phone: 'Phone',
  date: 'Date',
  type: 'Type',
  save: 'Save',
  cancel: 'Cancel',
  search: 'Search...',
  noData: 'No data available',
  actions: 'Actions',
  total: 'Total',
  login: 'Login',
  signup: 'Sign Up',
  email: 'Email',
  password: 'Password',
  confirmPassword: 'Confirm Password',
  loginButton: 'Log In',
  signupButton: 'Create Account',
  logout: 'Logout',
  noAccount: "Don't have an account?",
  haveAccount: 'Already have an account?',
  loginError: 'Invalid email or password',
  signupError: 'Error creating account',
  passwordMismatch: 'Passwords do not match',
  signupSuccess: 'Account created successfully! Please log in',
  emailNotConfirmed: 'Email not confirmed yet. Please check your inbox first',
  clients: 'Clients',
  addClient: 'New Client',
  editClient: 'Edit Client',
  deleteClient: 'Delete',
  deleteConfirm: 'Are you sure you want to delete?',
  clientName: 'Client Name',
  clientPhone: 'Phone Number',
  items: 'Items',
  addItem: 'Add Item',
  itemName: 'Item Name',
  quantity: 'Quantity',
  viewItems: 'View Items',
  eveningSummary: 'Evening Summary',
  itemsPerClient: 'Items per Client',
  totalQuantityPerItem: 'Total Quantity per Item',
  totalItems: 'Total Items',
  vegetableInventory: 'Vegetable Inventory',
  vegetableName: 'Vegetable Name',
  bought: 'Bought',
  sold: 'Sold',
  remaining: 'Remaining',
  addVegetable: 'Add Vegetable',
  dailyTotals: 'Daily Totals',
  chickenManagement: 'Chicken Management',
  chickenBought: 'Chicken Bought',
  chickenSold: 'Chicken Sold',
  numberOfChickens: 'Number of Chickens',
  weightKg: 'Weight (kg)',
  recordBought: 'Record Bought',
  recordSold: 'Record Sold',
  totalBought: 'Total Bought',
  totalSold: 'Total Sold',
  remainingQuantity: 'Remaining Quantity',
  remainingWeight: 'Remaining Weight (kg)',
  reports: 'Reports',
  dailySalesReport: 'Daily Sales Report',
  remainingStockReport: 'Remaining Stock Report',
  clientWiseReport: 'Client-wise Item Report',
  vegetablesSold: 'Vegetables Sold',
  chickenSoldReport: 'Chicken Sold',
  totalWeight: 'Total Weight',
  stock: 'Stock',
  home: 'Home',
  navAbout: 'About',
  navContact: 'Contact',
  tagline: 'Reliable Trade & Supply Services',
  heroDesc: 'Your trusted partner in gas cylinder supply, fresh chicken and vegetable trading. Consistent supply, fair pricing, and long-term business relationships.',
  heroCta: 'Contact Us',
  ourServices: 'Our Services',
  gasCylinders: 'Gas Cylinders',
  gasCylindersMainBiz: 'Main Business',
  gasCylindersDesc: 'Reliable LPG & Oxygen cylinder supply for domestic and commercial needs. Safety, timely delivery, and dependable service are our priority.',
  chickenTrading: 'Fresh Chicken',
  chickenTradingDesc: 'Daily fresh chicken buying and selling. Quality and freshness guaranteed.',
  vegetableTrading: 'Fresh Vegetables',
  vegetableTradingDesc: 'Daily supply of quality vegetables. Freshness and proper handling ensured.',
  aboutUs: 'About Us',
  aboutDesc: 'Jawad Traders is a trusted trading business specializing in the supply and distribution of gas cylinders. We are committed to providing the best service to our customers.',
  whyChooseUs: 'Why Choose Us?',
  trustedLocal: 'Trusted Business',
  trustedLocalDesc: 'Locally established, trusted by customers for years',
  consistentSupply: 'Consistent Supply',
  consistentSupplyDesc: 'Uninterrupted supply chain, always available',
  fairDealing: 'Transparent Dealing',
  fairDealingDesc: 'Fair pricing and clear business practices',
  customerFocused: 'Customer Focused',
  customerFocusedDesc: 'Your needs are our priority',
  contactUs: 'Contact Us',
  phoneWhatsApp: 'Phone / WhatsApp',
  emailLabel: 'Email',
  serviceArea: 'Service Area',
  serviceAreaValue: 'Snober City (Green Villas) Line 3',
  businessHours: 'Business Hours',
  businessHoursValue: '7 Days a Week\n7:30 AM – 12:00 AM',
  chatOnWhatsApp: 'Chat on WhatsApp',
  footerDesc: 'Your trusted partner in gas cylinder supply, fresh chicken and vegetable trading',
  footerTagline: 'Quality supply you can trust.',
  allRightsReserved: 'All rights reserved',
  cylinderTypes: 'Cylinder Types',
  addCylinderType: 'Add Cylinder Type',
  cylinderName: 'Cylinder Name',
  cylinderWeightKg: 'Weight (kg)',
  cylinderPrice: 'Cylinder Price',
  gasPrice: 'Gas Price',
  noOfCylinders: 'No. of Cylinders',
  editCylinderType: 'Edit',
  noCylinderTypes: 'No cylinder types yet',
  settings: 'Settings',
  manageVegetables: 'Vegetables List',
  addVegetableName: 'Add Vegetable',
  noVegetableNames: 'No vegetables added yet',
  editVegetableName: 'Edit',
  duplicateName: 'This name already exists',
  cylinderAssignments: 'Cylinder Assignments',
  assignCylinder: 'Assign Cylinder',
  selectClient: 'Select Client',
  selectCylinderType: 'Select Cylinder Type',
  available: 'Available',
  noCylinderAssignments: 'No assignments for this date',
  notEnoughCylinders: 'Not enough cylinders available',
  assigned: 'Assigned',
  soldExceedsRemaining: 'Sold cannot exceed remaining quantity',
  priceBought: 'Buy Price',
  priceSold: 'Sell Price',
  unit: 'Unit',
  unitKg: 'kg',
  unitDozen: 'Dozen',
  unitPiece: 'Piece',
  unitCrate: 'Crate',
  unitSack: 'Sack',
  todaySummary: "Today's Summary",
  cylindersAssignedToday: 'Cylinders Assigned Today',
  totalCylinders: 'Total Cylinders',
  unassigned: 'Unassigned',
  vegetableSummary: 'Vegetable Summary',
  totalBuyPrice: 'Total Buy Price',
  totalSellPrice: 'Total Sell Price',
  chickenSummary: 'Chicken Summary',
  totalQuantity: 'Total Quantity',
  profitLoss: 'Profit / Loss',
  profit: 'Profit',
  loss: 'Loss',
  price: 'Price',
  dailySales: 'Daily Sales',
  openingStock: 'Opening Stock',
  totalGasKg: 'Total Gas (kg)',
  totalCylindersOpening: 'Total Cylinders',
  saveDayOpening: 'Save',
  customerName: 'Customer Name',
  phoneNumber: 'Phone Number',
  totalAmount: 'Total Amount',
  paid: 'Paid',
  balance: 'Balance',
  addSale: 'Add Sale',
  noDailySales: 'No sales for this date',
  newCustomer: 'New Customer',
  customerBalance: 'Customer Balance',
  totalPaid: 'Total Paid',
  totalRemaining: 'Total Remaining',
  editOpening: 'Edit',
  saleType: 'Sale Type',
  gas: 'Gas',
  other: 'Other',
  gasKgSold: 'Gas (kg)',
  filterByName: 'Search by name',
  filterByPhone: 'Search by phone',
  previous: 'Previous',
  next: 'Next',
  page: 'Page',
  totalSale: 'Total Sale',
  successSaved: 'Saved successfully',
  successDeleted: 'Deleted successfully',
  errorOccurred: 'An error occurred',
  salary: 'Salary',
  employeeName: 'Employee Name',
  totalPay: 'Total Pay',
  addSalary: 'Add Salary',
  editSalary: 'Edit Salary',
  totalSalaries: 'Total Salaries',
  totalPaidSalary: 'Total Paid',
  totalRemainingSalary: 'Total Remaining',
  month: 'Month',
  newEmployee: 'New Employee',
  noSalaryRecords: 'No records for this month',
  employeeBalance: 'Employee Balance',
  suppliers: 'Suppliers',
  supplierName: 'Supplier Name',
  addSupplier: 'Add Supplier',
  editSupplier: 'Edit Supplier',
  totalBill: 'Total Bill',
  totalPaidSupplier: 'Total Paid',
  totalRemainingSupplier: 'Total Remaining',
  noSuppliers: 'No suppliers yet',
  newSupplier: 'New Supplier',
} as const

export type LabelKey = keyof typeof LABELS_UR
export type Labels = Record<LabelKey, string>

export const TRANSLATIONS: Record<Locale, Labels> = {
  ur: LABELS_UR,
  en: LABELS_EN,
}

export const NAV_KEYS = [
  { href: '/dashboard', labelKey: 'dashboard' as const, icon: '📊' },
  { href: '/daily-sales', labelKey: 'dailySales' as const, icon: '💰' },
  { href: '/cylinders', labelKey: 'cylinderAssignments' as const, icon: '🛢️' },
  { href: '/vegetables', labelKey: 'vegetableInventory' as const, icon: '🥬' },
  { href: '/chicken', labelKey: 'chickenManagement' as const, icon: '🍗' },
  { href: '/salary', labelKey: 'salary' as const, icon: '💵' },
  { href: '/suppliers', labelKey: 'suppliers' as const, icon: '🏭' },
] as const

export const SETTINGS_SUB_KEYS = [
  { href: '/settings/clients', labelKey: 'clients' as const, icon: '👥' },
  { href: '/settings/cylinder-types', labelKey: 'cylinderTypes' as const, icon: '🛢️' },
  { href: '/settings/vegetables', labelKey: 'manageVegetables' as const, icon: '🥬' },
] as const

export const VEGETABLE_UNITS = [
  { value: 'kg', labelKey: 'unitKg' as const },
  { value: 'dozen', labelKey: 'unitDozen' as const },
  { value: 'piece', labelKey: 'unitPiece' as const },
  { value: 'crate', labelKey: 'unitCrate' as const },
  { value: 'sack', labelKey: 'unitSack' as const },
] as const

export const CURRENCY = {
  code: 'PKR',
  symbol: 'Rs',
} as const

export const LOCALE_CONFIG: Record<Locale, { dir: 'rtl' | 'ltr'; htmlLang: string; dateLocale: string }> = {
  ur: { dir: 'rtl', htmlLang: 'ur', dateLocale: 'ur-PK' },
  en: { dir: 'ltr', htmlLang: 'en', dateLocale: 'en-PK' },
}
